#!/bin/bash

# Das ist eine mögliche Lösung für die Übungsidee zu den bash-Prozessen

status=3

count=$(ps -C bash | wc -l)

if [ $count -lt 3 ] ; then
    status=0
    statustxt=OK
elif [ $count -lt 6 ] ; then
    status=1
    statustxt=WARNING
else
    status=2
    statustxt=CRITICAL
fi

echo "$status BASH_PROC count=$count $statustxt - $count Prozesse mit namen bash"
