#!/bin/bash

# Holt die Seitenzahl und den Tonerstand vom Samsung-Drucker

seiten=`snmpget -v2c -Oqv -c public 10.1.2.4 iso.3.6.1.2.1.43.10.2.1.4.1.1`
tonerstand=`snmpget -v2c -Oqv -c public 10.1.2.4 1.3.6.1.2.1.43.11.1.1.9.1.1`

status=3
statustxt=UNDEF

if [ $tonerstand -gt 10 ] ; then
    status=0
    statustxt=OK
elif [ $tonerstand -gt 5 ] ; then
    status=1
    statustxt=WARNING
else
    status=2
    statustxt=CRITICAL
fi

echo "$status TONER toner=$tonerstand $statustxt - $tonerstand % Toner im Samsung-Drucker"

